create database DBMS_lab#8

USE DBMS_lab#8

CREATE TABLE EMP (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(50),
    JOB VARCHAR(50),
    MGR INT,
    HIREDATE DATE,
    SAL DECIMAL(10, 2),
    DEPTNO INT FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);
CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);

  SELECT * FROM EMP;
  SELECT * FROM DEPT;

  INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES
    (10, 'ACCOUNTING', 'NEW YORK'),
    (20, 'RESEARCH', 'DALLAS'),
    (30, 'SALES', 'CHICAGO');

  INSERT INTO EMP VALUES
    (7839, 'King', 'President', NULL, '1981-11-17', 5000.00, 10),
    (7566, 'Faisal', 'Manager', 7839, '1981-04-02', 2975.00, 20),
    (7698, 'Blake', 'Manager', 7839, '1981-05-01', 2850.00, 30),
    (7369, 'Farhan', 'Developer', 7566, '1981-06-09', 2450.00, 10),
    (7499, 'Talha', 'Salesman', 7499, '1981-02-20', 1600.00, 30)
   
   UPDATE EMP SET MGR=7698 WHERE EMPNO=7499

  SELECT EMPNO,HIREDATE FROM EMP
  where DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='Blake') 
  AND ENAME != 'Blake'; 

  SELECT EMPNO, ENAME,SAL FROM EMP
  WHERE SAL > (SELECT AVG(SAL) from EMP)

  SELECT EMPNO, ENAME FROM EMP
  WHERE DEPTNO = (SELECT  DEPTNO FROM EMP
                 WHERE ENAME LIKE '%T%');

SELECT EMPNO, ENAME
FROM EMP WHERE DEPTNO IN (
    SELECT DISTINCT DEPTNO FROM EMP
    WHERE ENAME LIKE '%T%'
);

SELECT EMPNO, ENAME FROM EMP
WHERE ENAME LIKE '%T%';

SELECT EMPNO, DEPTNO,JOB FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
              WHERE LOC='DALLAS');

SELECT ENAME, SAL FROM EMP
WHERE MGR=(SELECT EMPNO FROM EMP
              WHERE ENAME='King');


SELECT EMPNO,ENAME, SAL FROM EMP
WHERE SAL>(SELECT AVG(SAL) FROM EMP)
AND DEPTNO IN (
    SELECT DISTINCT DEPTNO
    FROM EMP
    WHERE ENAME LIKE '%T%'
);

SELECT EMPNO, ENAME FROM EMP
  WHERE DEPTNO = (SELECT  DEPTNO FROM EMP
                 WHERE ENAME LIKE '%T%');

